<?php
function get_countries_list_gh()
{
    return array(
        'AM' => array('name' => 'ARMENIA', 'phone' => '374'),
        'AD' => array('name' => 'ANDORRA', 'phone' => '376'),
        'AE' => array('name' => 'UNITED ARAB EMIRATES', 'phone' => '971'),
        'AF' => array('name' => 'AFGHANISTAN', 'phone' => '93'),
        'AG' => array('name' => 'ANTIGUA AND BARBUDA', 'phone' => '1268'),
        'AI' => array('name' => 'ANGUILLA', 'phone' => '1264'),
        'AL' => array('name' => 'ALBANIA', 'phone' => '355'),
        'AN' => array('name' => 'NETHERLANDS ANTILLES', 'phone' => '599'),
        'AO' => array('name' => 'ANGOLA', 'phone' => '244'),
        'AQ' => array('name' => 'ANTARCTICA', 'phone' => '672'),
        'AR' => array('name' => 'ARGENTINA', 'phone' => '54'),
        'AS' => array('name' => 'AMERICAN SAMOA', 'phone' => '1684'),
        'AT' => array('name' => 'AUSTRIA', 'phone' => '43'),
        'AU' => array('name' => 'AUSTRALIA', 'phone' => '61'),
        'AW' => array('name' => 'ARUBA', 'phone' => '297'),
        'AZ' => array('name' => 'AZERBAIJAN', 'phone' => '994'),
        'BA' => array('name' => 'BOSNIA AND HERZEGOVINA', 'phone' => '387'),
        'BB' => array('name' => 'BARBADOS', 'phone' => '1246'),
        'BD' => array('name' => 'BANGLADESH', 'phone' => '880'),
        'BE' => array('name' => 'BELGIUM', 'phone' => '32'),
        'BF' => array('name' => 'BURKINA FASO', 'phone' => '226'),
        'BG' => array('name' => 'BULGARIA', 'phone' => '359'),
        'BH' => array('name' => 'BAHRAIN', 'phone' => '973'),
        'BI' => array('name' => 'BURUNDI', 'phone' => '257'),
        'BJ' => array('name' => 'BENIN', 'phone' => '229'),
        'BL' => array('name' => 'SAINT BARTHELEMY', 'phone' => '590'),
        'BM' => array('name' => 'BERMUDA', 'phone' => '1441'),
        'BN' => array('name' => 'BRUNEI DARUSSALAM', 'phone' => '673'),
        'BO' => array('name' => 'BOLIVIA', 'phone' => '591'),
        'BR' => array('name' => 'BRAZIL', 'phone' => '55'),
        'BS' => array('name' => 'BAHAMAS', 'phone' => '1242'),
        'BT' => array('name' => 'BHUTAN', 'phone' => '975'),
        'BW' => array('name' => 'BOTSWANA', 'phone' => '267'),
        'BY' => array('name' => 'BELARUS', 'phone' => '375'),
        'BZ' => array('name' => 'BELIZE', 'phone' => '501'),
        'CA' => array('name' => 'CANADA', 'phone' => '1'),
        'CC' => array('name' => 'COCOS (KEELING) ISLANDS', 'phone' => '61'),
        'CD' => array('name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'phone' => '243'),
        'CF' => array('name' => 'CENTRAL AFRICAN REPUBLIC', 'phone' => '236'),
        'CG' => array('name' => 'CONGO', 'phone' => '242'),
        'CH' => array('name' => 'SWITZERLAND', 'phone' => '41'),
        'CI' => array('name' => 'COTE D IVOIRE', 'phone' => '225'),
        'CK' => array('name' => 'COOK ISLANDS', 'phone' => '682'),
        'CL' => array('name' => 'CHILE', 'phone' => '56'),
        'CM' => array('name' => 'CAMEROON', 'phone' => '237'),
        'CN' => array('name' => 'CHINA', 'phone' => '86'),
        'CO' => array('name' => 'COLOMBIA', 'phone' => '57'),
        'CR' => array('name' => 'COSTA RICA', 'phone' => '506'),
        'CU' => array('name' => 'CUBA', 'phone' => '53'),
        'CV' => array('name' => 'CAPE VERDE', 'phone' => '238'),
        'CX' => array('name' => 'CHRISTMAS ISLAND', 'phone' => '61'),
        'CY' => array('name' => 'CYPRUS', 'phone' => '357'),
        'CZ' => array('name' => 'CZECH REPUBLIC', 'phone' => '420'),
        'DE' => array('name' => 'GERMANY', 'phone' => '49'),
        'DJ' => array('name' => 'DJIBOUTI', 'phone' => '253'),
        'DK' => array('name' => 'DENMARK', 'phone' => '45'),
        'DM' => array('name' => 'DOMINICA', 'phone' => '1767'),
        'DO' => array('name' => 'DOMINICAN REPUBLIC', 'phone' => '1809'),
        'DZ' => array('name' => 'ALGERIA', 'phone' => '213'),
        'EC' => array('name' => 'ECUADOR', 'phone' => '593'),
        'EE' => array('name' => 'ESTONIA', 'phone' => '372'),
        'EG' => array('name' => 'EGYPT', 'phone' => '20'),
        'ER' => array('name' => 'ERITREA', 'phone' => '291'),
        'ES' => array('name' => 'SPAIN', 'phone' => '34'),
        'ET' => array('name' => 'ETHIOPIA', 'phone' => '251'),
        'FI' => array('name' => 'FINLAND', 'phone' => '358'),
        'FJ' => array('name' => 'FIJI', 'phone' => '679'),
        'FK' => array('name' => 'FALKLAND ISLANDS (MALVINAS)', 'phone' => '500'),
        'FM' => array('name' => 'MICRONESIA, FEDERATED STATES OF', 'phone' => '691'),
        'FO' => array('name' => 'FAROE ISLANDS', 'phone' => '298'),
        'FR' => array('name' => 'FRANCE', 'phone' => '33'),
        'GA' => array('name' => 'GABON', 'phone' => '241'),
        'GB' => array('name' => 'UNITED KINGDOM', 'phone' => '44'),
        'GD' => array('name' => 'GRENADA', 'phone' => '1473'),
        'GE' => array('name' => 'GEORGIA', 'phone' => '995'),
        'GH' => array('name' => 'GHANA', 'phone' => '233'),
        'GI' => array('name' => 'GIBRALTAR', 'phone' => '350'),
        'GL' => array('name' => 'GREENLAND', 'phone' => '299'),
        'GM' => array('name' => 'GAMBIA', 'phone' => '220'),
        'GN' => array('name' => 'GUINEA', 'phone' => '224'),
        'GQ' => array('name' => 'EQUATORIAL GUINEA', 'phone' => '240'),
        'GR' => array('name' => 'GREECE', 'phone' => '30'),
        'GT' => array('name' => 'GUATEMALA', 'phone' => '502'),
        'GU' => array('name' => 'GUAM', 'phone' => '1671'),
        'GW' => array('name' => 'GUINEA-BISSAU', 'phone' => '245'),
        'GY' => array('name' => 'GUYANA', 'phone' => '592'),
        'HK' => array('name' => 'HONG KONG', 'phone' => '852'),
        'HN' => array('name' => 'HONDURAS', 'phone' => '504'),
        'HR' => array('name' => 'CROATIA', 'phone' => '385'),
        'HT' => array('name' => 'HAITI', 'phone' => '509'),
        'HU' => array('name' => 'HUNGARY', 'phone' => '36'),
        'ID' => array('name' => 'INDONESIA', 'phone' => '62'),
        'IE' => array('name' => 'IRELAND', 'phone' => '353'),
        'IL' => array('name' => 'ISRAEL', 'phone' => '972'),
        'IM' => array('name' => 'ISLE OF MAN', 'phone' => '44'),
        'IN' => array('name' => 'INDIA', 'phone' => '91'),
        'IQ' => array('name' => 'IRAQ', 'phone' => '964'),
        'IR' => array('name' => 'IRAN, ISLAMIC REPUBLIC OF', 'phone' => '98'),
        'IS' => array('name' => 'ICELAND', 'phone' => '354'),
        'IT' => array('name' => 'ITALY', 'phone' => '39'),
        'JM' => array('name' => 'JAMAICA', 'phone' => '1876'),
        'JO' => array('name' => 'JORDAN', 'phone' => '962'),
        'JP' => array('name' => 'JAPAN', 'phone' => '81'),
        'KE' => array('name' => 'KENYA', 'phone' => '254'),
        'KG' => array('name' => 'KYRGYZSTAN', 'phone' => '996'),
        'KH' => array('name' => 'CAMBODIA', 'phone' => '855'),
        'KI' => array('name' => 'KIRIBATI', 'phone' => '686'),
        'KM' => array('name' => 'COMOROS', 'phone' => '269'),
        'KN' => array('name' => 'SAINT KITTS AND NEVIS', 'phone' => '1869'),
        'KP' => array('name' => 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', 'phone' => '850'),
        'KR' => array('name' => 'KOREA REPUBLIC OF', 'phone' => '82'),
        'KW' => array('name' => 'KUWAIT', 'phone' => '965'),
        'KY' => array('name' => 'CAYMAN ISLANDS', 'phone' => '1345'),
        'KZ' => array('name' => 'KAZAKSTAN', 'phone' => '7'),
        'LA' => array('name' => 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'phone' => '856'),
        'LB' => array('name' => 'LEBANON', 'phone' => '961'),
        'LC' => array('name' => 'SAINT LUCIA', 'phone' => '1758'),
        'LI' => array('name' => 'LIECHTENSTEIN', 'phone' => '423'),
        'LK' => array('name' => 'SRI LANKA', 'phone' => '94'),
        'LR' => array('name' => 'LIBERIA', 'phone' => '231'),
        'LS' => array('name' => 'LESOTHO', 'phone' => '266'),
        'LT' => array('name' => 'LITHUANIA', 'phone' => '370'),
        'LU' => array('name' => 'LUXEMBOURG', 'phone' => '352'),
        'LV' => array('name' => 'LATVIA', 'phone' => '371'),
        'LY' => array('name' => 'LIBYAN ARAB JAMAHIRIYA', 'phone' => '218'),
        'MA' => array('name' => 'MOROCCO', 'phone' => '212'),
        'MC' => array('name' => 'MONACO', 'phone' => '377'),
        'MD' => array('name' => 'MOLDOVA, REPUBLIC OF', 'phone' => '373'),
        'ME' => array('name' => 'MONTENEGRO', 'phone' => '382'),
        'MF' => array('name' => 'SAINT MARTIN', 'phone' => '1599'),
        'MG' => array('name' => 'MADAGASCAR', 'phone' => '261'),
        'MH' => array('name' => 'MARSHALL ISLANDS', 'phone' => '692'),
        'MK' => array('name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'phone' => '389'),
        'ML' => array('name' => 'MALI', 'phone' => '223'),
        'MM' => array('name' => 'MYANMAR', 'phone' => '95'),
        'MN' => array('name' => 'MONGOLIA', 'phone' => '976'),
        'MO' => array('name' => 'MACAU', 'phone' => '853'),
        'MP' => array('name' => 'NORTHERN MARIANA ISLANDS', 'phone' => '1670'),
        'MR' => array('name' => 'MAURITANIA', 'phone' => '222'),
        'MS' => array('name' => 'MONTSERRAT', 'phone' => '1664'),
        'MT' => array('name' => 'MALTA', 'phone' => '356'),
        'MU' => array('name' => 'MAURITIUS', 'phone' => '230'),
        'MV' => array('name' => 'MALDIVES', 'phone' => '960'),
        'MW' => array('name' => 'MALAWI', 'phone' => '265'),
        'MX' => array('name' => 'MEXICO', 'phone' => '52'),
        'MY' => array('name' => 'MALAYSIA', 'phone' => '60'),
        'MZ' => array('name' => 'MOZAMBIQUE', 'phone' => '258'),
        'NA' => array('name' => 'NAMIBIA', 'phone' => '264'),
        'NC' => array('name' => 'NEW CALEDONIA', 'phone' => '687'),
        'NE' => array('name' => 'NIGER', 'phone' => '227'),
        'NG' => array('name' => 'NIGERIA', 'phone' => '234'),
        'NI' => array('name' => 'NICARAGUA', 'phone' => '505'),
        'NL' => array('name' => 'NETHERLANDS', 'phone' => '31'),
        'NO' => array('name' => 'NORWAY', 'phone' => '47'),
        'NP' => array('name' => 'NEPAL', 'phone' => '977'),
        'NR' => array('name' => 'NAURU', 'phone' => '674'),
        'NU' => array('name' => 'NIUE', 'phone' => '683'),
        'NZ' => array('name' => 'NEW ZEALAND', 'phone' => '64'),
        'OM' => array('name' => 'OMAN', 'phone' => '968'),
        'PA' => array('name' => 'PANAMA', 'phone' => '507'),
        'PE' => array('name' => 'PERU', 'phone' => '51'),
        'PF' => array('name' => 'FRENCH POLYNESIA', 'phone' => '689'),
        'PG' => array('name' => 'PAPUA NEW GUINEA', 'phone' => '675'),
        'PH' => array('name' => 'PHILIPPINES', 'phone' => '63'),
        'PK' => array('name' => 'PAKISTAN', 'phone' => '92'),
        'PL' => array('name' => 'POLAND', 'phone' => '48'),
        'PM' => array('name' => 'SAINT PIERRE AND MIQUELON', 'phone' => '508'),
        'PN' => array('name' => 'PITCAIRN', 'phone' => '870'),
        'PR' => array('name' => 'PUERTO RICO', 'phone' => '1'),
        'PT' => array('name' => 'PORTUGAL', 'phone' => '351'),
        'PW' => array('name' => 'PALAU', 'phone' => '680'),
        'PY' => array('name' => 'PARAGUAY', 'phone' => '595'),
        'QA' => array('name' => 'QATAR', 'phone' => '974'),
        'RO' => array('name' => 'ROMANIA', 'phone' => '40'),
        'RS' => array('name' => 'SERBIA', 'phone' => '381'),
        'RU' => array('name' => 'RUSSIAN FEDERATION', 'phone' => '7'),
        'RW' => array('name' => 'RWANDA', 'phone' => '250'),
        'SA' => array('name' => 'SAUDI ARABIA', 'phone' => '966'),
        'SB' => array('name' => 'SOLOMON ISLANDS', 'phone' => '677'),
        'SC' => array('name' => 'SEYCHELLES', 'phone' => '248'),
        'SD' => array('name' => 'SUDAN', 'phone' => '249'),
        'SE' => array('name' => 'SWEDEN', 'phone' => '46'),
        'SG' => array('name' => 'SINGAPORE', 'phone' => '65'),
        'SH' => array('name' => 'SAINT HELENA', 'phone' => '290'),
        'SI' => array('name' => 'SLOVENIA', 'phone' => '386'),
        'SK' => array('name' => 'SLOVAKIA', 'phone' => '421'),
        'SL' => array('name' => 'SIERRA LEONE', 'phone' => '232'),
        'SM' => array('name' => 'SAN MARINO', 'phone' => '378'),
        'SN' => array('name' => 'SENEGAL', 'phone' => '221'),
        'SO' => array('name' => 'SOMALIA', 'phone' => '252'),
        'SR' => array('name' => 'SURINAME', 'phone' => '597'),
        'ST' => array('name' => 'SAO TOME AND PRINCIPE', 'phone' => '239'),
        'SV' => array('name' => 'EL SALVADOR', 'phone' => '503'),
        'SY' => array('name' => 'SYRIAN ARAB REPUBLIC', 'phone' => '963'),
        'SZ' => array('name' => 'SWAZILAND', 'phone' => '268'),
        'TC' => array('name' => 'TURKS AND CAICOS ISLANDS', 'phone' => '1649'),
        'TD' => array('name' => 'CHAD', 'phone' => '235'),
        'TG' => array('name' => 'TOGO', 'phone' => '228'),
        'TH' => array('name' => 'THAILAND', 'phone' => '66'),
        'TJ' => array('name' => 'TAJIKISTAN', 'phone' => '992'),
        'TK' => array('name' => 'TOKELAU', 'phone' => '690'),
        'TL' => array('name' => 'TIMOR-LESTE', 'phone' => '670'),
        'TM' => array('name' => 'TURKMENISTAN', 'phone' => '993'),
        'TN' => array('name' => 'TUNISIA', 'phone' => '216'),
        'TO' => array('name' => 'TONGA', 'phone' => '676'),
        'TR' => array('name' => 'TURKEY', 'phone' => '90'),
        'TT' => array('name' => 'TRINIDAD AND TOBAGO', 'phone' => '1868'),
        'TV' => array('name' => 'TUVALU', 'phone' => '688'),
        'TW' => array('name' => 'TAIWAN, PROVINCE OF CHINA', 'phone' => '886'),
        'TZ' => array('name' => 'TANZANIA, UNITED REPUBLIC OF', 'phone' => '255'),
        'UA' => array('name' => 'UKRAINE', 'phone' => '380'),
        'UG' => array('name' => 'UGANDA', 'phone' => '256'),
        'US' => array('name' => 'UNITED STATES', 'phone' => '1'),
        'UY' => array('name' => 'URUGUAY', 'phone' => '598'),
        'UZ' => array('name' => 'UZBEKISTAN', 'phone' => '998'),
        'VA' => array('name' => 'HOLY SEE (VATICAN CITY STATE)', 'phone' => '39'),
        'VC' => array('name' => 'SAINT VINCENT AND THE GRENADINES', 'phone' => '1784'),
        'VE' => array('name' => 'VENEZUELA', 'phone' => '58'),
        'VG' => array('name' => 'VIRGIN ISLANDS, BRITISH', 'phone' => '1284'),
        'VI' => array('name' => 'VIRGIN ISLANDS, U.S.', 'phone' => '1340'),
        'VN' => array('name' => 'VIET NAM', 'phone' => '84'),
        'VU' => array('name' => 'VANUATU', 'phone' => '678'),
        'WF' => array('name' => 'WALLIS AND FUTUNA', 'phone' => '681'),
        'WS' => array('name' => 'SAMOA', 'phone' => '685'),
        'XK' => array('name' => 'KOSOVO', 'phone' => '381'),
        'YE' => array('name' => 'YEMEN', 'phone' => '967'),
        'YT' => array('name' => 'MAYOTTE', 'phone' => '262'),
        'ZA' => array('name' => 'SOUTH AFRICA', 'phone' => '27'),
        'ZM' => array('name' => 'ZAMBIA', 'phone' => '260'),
        'ZW' => array('name' => 'ZIMBABWE', 'phone' => '263')
    );
}

